site_name: sourcelib-docs
site_url: https://github.com/uqembeddedsys-projects/sourcelib-docs
repo_url: https://github.com/uqembeddedsys-projects/sourcelib-docs
repo_name:  sourcelib-docs

nav:
- Home: 'index.md'
- Git: 'git/git.md'
- Setup:
    - 'Virtual Machine': 'setup/virtual_machine/virtual_machine.md'
    - 'Linux Setup Installation': 'setup/linux/linux.md'
- Getting Started:
    - 'Blinky': 'getting_started/blinky.md'
- VSCode and Debugging:
    - 'VSCode Settings': 'setup/vsworkspace/vsworkspace.md'
    - 'Debugger': 'setup/debug/debug.md'

theme: readthedocs
markdown_extensions:
    - toc:
        baselevel: 3
        separator: "_"