site_name: CSSE3010Docs
site_url: https://uqembeddedsys-projects.github.io/sourcelib-docs
nav:
- Home: 'index.md'
- Git: 'git/git.md'
- Setup:
    - 'Virtual Machine': 'setup/virtual_machine/virtual_machine.md'
    - 'Native Linux Setup Installation': 'setup/linux/linux.md'
- Getting Started:
    - 'Blinky': 'getting_started/blinky.md'

theme: readthedocs
markdown_extensions:
    - toc:
        baselevel: 3
        separator: "_"